[package]
name = "organn"
version = "0.4.0"
authors = ["monsieursquirrel <conrad@bebbington.org>"]

[dependencies]
coreaudio-rs = "0.2.0"
pitch_calc = "0.9.7"
midi = "0.1.0"
rb = "0.2.0"

[dependencies.midi_wrap]
path = "lib/midi_wrap"
